name: "Bump license year"
on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 1 1 *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    if: github.repository == 'stacklok/minder' # Only run on the main repository and not forks
    name: Bump license year
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set Current Year
        run: |
          echo "YEAR=$(date +'%Y')" >> "$GITHUB_ENV"

      - name: Modify Files
        run: |
          ./.ci/bump-license-year.sh $(("${{ env.YEAR }}" - 1)) ${{ env.YEAR }} .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          commit-message: "Bump license year to ${{ env.YEAR }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: "bump-license-year-${{ env.YEAR }}"
          delete-branch: true
          title: "Bump license year to ${{ env.YEAR }}"
          body: |
              Bump license year to ${{ env.YEAR }}.
    
              This is an automated pull request generated by a GitHub Action.
          labels: |
            automated pr
          draft: false
